<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Fonts\Inter-Thin.ttf" />
    <Resource Include="Fonts\Inter-ExtraLight.ttf" />
    <Resource Include="Fonts\Inter-Light.ttf" />
    <Resource Include="Fonts\Inter-Regular.ttf" />
    <Resource Include="Fonts\Inter-Medium.ttf" />
    <Resource Include="Fonts\Inter-SemiBold.ttf" />
    <Resource Include="Fonts\Inter-Bold.ttf" />
    <Resource Include="Fonts\Inter-ExtraBold.ttf" />
    <Resource Include="Fonts\Inter-Black.ttf" />
    <Resource Include="Fonts\InterVariable.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>

</Project>
