<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Icons\IconApp.ico</ApplicationIcon>
    <Version>1.5.1</Version>
    <AssemblyVersion>1.5.1.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Lame" Version="2.1.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3674" />
    <PackageReference Include="WTelegramClient" Version="4.4.4" />
    <PackageReference Include="libphonenumber-csharp" Version="9.0.34" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Infrastructure\AppSecrets.example.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Icons\IconApp.png" />
    <None Remove="Assets\Icons\ringostat.png" />
    <None Remove="Assets\Icons\telegram.png" />
    <None Remove="Assets\Icons\viber.png" />
    <None Remove="Assets\Icons\whatsapp.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Icons\IconApp.png" />
    <Resource Include="Assets\Icons\ringostat.png" />
    <Resource Include="Assets\Icons\telegram.png" />
    <Resource Include="Assets\Icons\viber.png" />
    <Resource Include="Assets\Icons\whatsapp.png" />
    <Resource Include="Fonts\Inter-Thin.ttf" />
    <Resource Include="Fonts\Inter-ExtraLight.ttf" />
    <Resource Include="Fonts\Inter-Light.ttf" />
    <Resource Include="Fonts\Inter-Regular.ttf" />
    <Resource Include="Fonts\Inter-Medium.ttf" />
    <Resource Include="Fonts\Inter-SemiBold.ttf" />
    <Resource Include="Fonts\Inter-Bold.ttf" />
    <Resource Include="Fonts\Inter-ExtraBold.ttf" />
    <Resource Include="Fonts\Inter-Black.ttf" />
    <Resource Include="Fonts\InterVariable.ttf" />
  </ItemGroup>

</Project>
